import { INodeProperties } from 'n8n-workflow';

export const contactOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['contact'] } },
		options: [
			{
				name: 'Custom API Call',
				value: 'customApiCall',
				description:
					'See the notice below — use the HTTP Request node for endpoints not yet wired up here',
				action: 'Custom API call',
			},
			{
				name: 'Get',
				value: 'get',
				description:
					'Get one or more contacts by ID via /contact-service/contact/{ID-SET}. Accepts ID sets (single, range, or comma list).',
				action: 'Get a contact',
			},
			{
				name: 'Get Many',
				value: 'getMany',
				description: 'Search contacts via /contact-service/contact-search',
				action: 'Get many contacts',
			},
		],
		default: 'get',
	},
];

export const contactFields: INodeProperties[] = [
	// ─── GET ──────────────────────────────────────────────────────────────────
	{
		displayName: 'Contact ID',
		name: 'contactId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['contact'], operation: ['get'] } },
		description:
			'The Brightpearl contact ID. ID set syntax supported: single (200), ascending range (200-210), or comma list (1,2,3). Brightpearl caps an unfiltered request at 200 contacts.',
	},

	// ─── GET MANY ─────────────────────────────────────────────────────────────
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		displayOptions: { show: { resource: ['contact'], operation: ['getMany'] } },
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Columns to Return',
		name: 'contactColumns',
		type: 'multiOptions',
		default: [],
		displayOptions: { show: { resource: ['contact'], operation: ['getMany'] } },
		description:
			'Pick which contact-search columns to return. Leave empty for the Brightpearl defaults.',
		options: [
			{ name: 'Company Name', value: 'companyName' },
			{ name: 'Contact ID', value: 'contactId' },
			{ name: 'Created On', value: 'createdOn' },
			{ name: 'Exact Company Name', value: 'exactCompanyName' },
			{ name: 'First Name', value: 'firstName' },
			{ name: 'Is Customer', value: 'isCustomer' },
			{ name: 'Is Primary', value: 'isPrimary' },
			{ name: 'Is Staff', value: 'isStaff' },
			{ name: 'Is Supplier', value: 'isSupplier' },
			{ name: 'Last Contacted On', value: 'lastContactedOn' },
			{ name: 'Last Name', value: 'lastName' },
			{ name: 'Last Ordered On', value: 'lastOrderedOn' },
			{ name: 'Mobile Phone', value: 'mob' },
			{ name: 'Nominal Code', value: 'nominalCode' },
			{ name: 'Primary Email', value: 'primaryEmail' },
			{ name: 'Primary Phone', value: 'pri' },
			{ name: 'Secondary Email', value: 'secondaryEmail' },
			{ name: 'Secondary Phone', value: 'sec' },
			{ name: 'Tertiary Email', value: 'tertiaryEmail' },
			{ name: 'Title', value: 'title' },
			{ name: 'Updated On', value: 'updatedOn' },
		],
	},
	{
		displayName: 'Filters',
		name: 'contactFilters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: { resource: ['contact'], operation: ['getMany'] } },
		options: [
			{
				displayName: 'Company Name',
				name: 'companyName',
				type: 'string',
				default: '',
				description:
					'Case-insensitive substring match on company name. Use Exact Company Name for an exact match.',
			},
			{
				displayName: 'Contact ID',
				name: 'contactId',
				type: 'string',
				default: '',
				description: 'Filter by contact ID. ID set syntax supported.',
			},
			{
				displayName: 'Created On (From)',
				name: 'createdOnFrom',
				type: 'dateTime',
				default: '',
				description: 'Return contacts created on or after this date/time',
			},
			{
				displayName: 'Created On (To)',
				name: 'createdOnTo',
				type: 'dateTime',
				default: '',
				description: 'Return contacts created on or before this date/time',
			},
			{
				displayName: 'Exact Company Name',
				name: 'exactCompanyName',
				type: 'string',
				default: '',
				description: 'Filter by exact company-name match',
			},
			{
				displayName: 'First Name',
				name: 'firstName',
				type: 'string',
				default: '',
				description: 'Case-insensitive substring match on first name',
			},
			{
				displayName: 'Is Customer',
				name: 'isCustomer',
				type: 'boolean',
				default: true,
				description: 'Whether to include only customer-flagged contacts',
			},
			{
				displayName: 'Is Primary',
				name: 'isPrimary',
				type: 'boolean',
				default: true,
				description:
					'Whether to include only contacts that are the primary contact of their organisation',
			},
			{
				displayName: 'Is Staff',
				name: 'isStaff',
				type: 'boolean',
				default: true,
				description: 'Whether to include only staff-flagged contacts',
			},
			{
				displayName: 'Is Supplier',
				name: 'isSupplier',
				type: 'boolean',
				default: true,
				description: 'Whether to include only supplier-flagged contacts',
			},
			{
				displayName: 'Last Contacted On (From)',
				name: 'lastContactedOnFrom',
				type: 'dateTime',
				default: '',
				description: 'Return contacts last contacted on or after this date/time',
			},
			{
				displayName: 'Last Contacted On (To)',
				name: 'lastContactedOnTo',
				type: 'dateTime',
				default: '',
				description: 'Return contacts last contacted on or before this date/time',
			},
			{
				displayName: 'Last Name',
				name: 'lastName',
				type: 'string',
				default: '',
				description: 'Case-insensitive substring match on last name',
			},
			{
				displayName: 'Last Ordered On (From)',
				name: 'lastOrderedOnFrom',
				type: 'dateTime',
				default: '',
				description: 'Return contacts whose last order was on or after this date',
			},
			{
				displayName: 'Last Ordered On (To)',
				name: 'lastOrderedOnTo',
				type: 'dateTime',
				default: '',
				description: 'Return contacts whose last order was on or before this date',
			},
			{
				displayName: 'Mobile Phone',
				name: 'mob',
				type: 'string',
				default: '',
				description: 'Filter by mobile phone number',
			},
			{
				displayName: 'Nominal Code',
				name: 'nominalCode',
				type: 'number',
				default: 0,
				description: 'Filter by financial nominal code',
			},
			{
				displayName: 'Primary Email',
				name: 'primaryEmail',
				type: 'string',
				default: '',
				description: 'Case-insensitive substring match on primary email',
			},
			{
				displayName: 'Primary Phone',
				name: 'pri',
				type: 'string',
				default: '',
				description: 'Filter by primary phone number',
			},
			{
				displayName: 'Secondary Email',
				name: 'secondaryEmail',
				type: 'string',
				default: '',
				description: 'Case-insensitive substring match on secondary email',
			},
			{
				displayName: 'Secondary Phone',
				name: 'sec',
				type: 'string',
				default: '',
				description: 'Filter by secondary phone number',
			},
			{
				displayName: 'Tertiary Email',
				name: 'tertiaryEmail',
				type: 'string',
				default: '',
				description: 'Case-insensitive substring match on tertiary email',
			},
			{
				displayName: 'Title',
				name: 'title',
				type: 'string',
				default: '',
				description: 'Filter by job title',
			},
			{
				displayName: 'Updated On (From)',
				name: 'updatedOnFrom',
				type: 'dateTime',
				default: '',
				description: 'Return contacts last updated on or after this date/time',
			},
			{
				displayName: 'Updated On (To)',
				name: 'updatedOnTo',
				type: 'dateTime',
				default: '',
				description: 'Return contacts last updated on or before this date/time',
			},
		],
	},
	{
		displayName: 'Sort',
		name: 'contactSort',
		type: 'collection',
		placeholder: 'Add Sort',
		default: {},
		displayOptions: { show: { resource: ['contact'], operation: ['getMany'] } },
		description:
			'Optional: sort results by a contact-search column. Default Brightpearl order is by contactId ascending.',
		options: [
			{
				displayName: 'Direction',
				name: 'direction',
				type: 'options',
				default: 'DESC',
				options: [
					{ name: 'Ascending', value: 'ASC' },
					{ name: 'Descending', value: 'DESC' },
				],
			},
			{
				displayName: 'Sort By',
				name: 'sortBy',
				type: 'options',
				default: 'createdOn',
				options: [
					{ name: 'Company Name', value: 'companyName' },
					{ name: 'Contact ID', value: 'contactId' },
					{ name: 'Created On', value: 'createdOn' },
					{ name: 'First Name', value: 'firstName' },
					{ name: 'Last Contacted On', value: 'lastContactedOn' },
					{ name: 'Last Name', value: 'lastName' },
					{ name: 'Last Ordered On', value: 'lastOrderedOn' },
					{ name: 'Nominal Code', value: 'nominalCode' },
					{ name: 'Primary Email', value: 'primaryEmail' },
					{ name: 'Title', value: 'title' },
					{ name: 'Updated On', value: 'updatedOn' },
				],
			},
		],
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		typeOptions: { minValue: 1 },
		displayOptions: {
			show: { resource: ['contact'], operation: ['getMany'], returnAll: [false] },
		},
		description: 'Max number of results to return',
	},
	{
		displayName: 'First Result',
		name: 'firstResult',
		type: 'number',
		default: 1,
		typeOptions: { minValue: 1 },
		displayOptions: {
			show: { resource: ['contact'], operation: ['getMany'], returnAll: [false] },
		},
		description:
			'1-indexed starting position. Combine with Limit to paginate. Use the _pagination metadata on returned items to see how many total results exist.',
	},
	{
		displayName: 'Batching',
		name: 'batching',
		type: 'collection',
		placeholder: 'Add Batching Option',
		default: {},
		displayOptions: {
			show: { resource: ['contact'], operation: ['getMany'], returnAll: [true] },
		},
		description:
			'Optional: pace the page-by-page fetch so large queries do not exhaust the Brightpearl quota and trip the rate-limit retry loop',
		options: [
			{
				displayName: 'Delay Between Pages (Ms)',
				name: 'pageDelayMs',
				type: 'number',
				default: 0,
				typeOptions: { minValue: 0 },
				description:
					'How long to wait between consecutive page requests. Try 500–1000 if you are hitting 503 errors on large fetches.',
			},
			{
				displayName: 'Page Size',
				name: 'pageSize',
				type: 'number',
				default: 200,
				typeOptions: { minValue: 1, maxValue: 200 },
				description:
					'How many results per Brightpearl page request. Lower values use more API calls but each call is cheaper against the quota.',
			},
		],
	},
];
