import { INodeProperties } from 'n8n-workflow';

export const productOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['product'] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				description: 'Create a new product',
				action: 'Create a product',
			},
			{
				name: 'Custom API Call',
				value: 'customApiCall',
				description:
					'See the notice below — use the HTTP Request node for endpoints not yet wired up here',
				action: 'Custom API call',
			},
			{
				name: 'Get',
				value: 'get',
				description: 'Get a single product by ID',
				action: 'Get a product',
			},
			{
				name: 'Get Many',
				value: 'getMany',
				description: 'Search and retrieve multiple products',
				action: 'Get many products',
			},
		],
		default: 'get',
	},
];

export const productFields: INodeProperties[] = [
	// ─── GET ──────────────────────────────────────────────────────────────────
	{
		displayName: 'Product ID',
		name: 'productId',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['product'], operation: ['get'] } },
		description: 'The Brightpearl product ID',
	},

	// ─── GET MANY ─────────────────────────────────────────────────────────────
	// Same layout as the Order search: returnAll, then columns/filters/sort,
	// then pagination at the bottom.
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		displayOptions: { show: { resource: ['product'], operation: ['getMany'] } },
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Columns to Return',
		name: 'productColumns',
		type: 'multiOptions',
		default: [],
		displayOptions: { show: { resource: ['product'], operation: ['getMany'] } },
		description:
			'Pick which product-search columns to return. Leave empty for the Brightpearl defaults.',
		options: [
			{ name: 'Barcode', value: 'barcode' },
			{ name: 'Brand ID', value: 'brandId' },
			{ name: 'Category ID', value: 'categoryId' },
			{ name: 'Created On', value: 'createdOn' },
			{ name: 'EAN', value: 'EAN' },
			{ name: 'ISBN', value: 'ISBN' },
			{ name: 'Is Active', value: 'isActive' },
			{ name: 'MPN', value: 'MPN' },
			{ name: 'Primary Supplier ID', value: 'primarySupplierId' },
			{ name: 'Product ID', value: 'productId' },
			{ name: 'Product Name', value: 'productName' },
			{ name: 'Product Type ID', value: 'productTypeId' },
			{ name: 'SKU', value: 'SKU' },
			{ name: 'Status', value: 'status' },
			{ name: 'Stock Tracked', value: 'stockTracked' },
			{ name: 'UPC', value: 'UPC' },
			{ name: 'Updated On', value: 'updatedOn' },
		],
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: { resource: ['product'], operation: ['getMany'] } },
		options: [
			{
				displayName: 'Barcode',
				name: 'barcode',
				type: 'string',
				default: '',
				description: 'Filter by exact barcode',
			},
			{
				displayName: 'Brand ID',
				name: 'brandId',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Category ID',
				name: 'categoryId',
				type: 'string',
				default: '',
				description: 'Filter by category ID. ID set syntax supported.',
			},
			{
				displayName: 'Created On (From)',
				name: 'createdOnFrom',
				type: 'dateTime',
				default: '',
				description: 'Return products created on or after this date/time',
			},
			{
				displayName: 'Created On (To)',
				name: 'createdOnTo',
				type: 'dateTime',
				default: '',
				description: 'Return products created on or before this date/time',
			},
			{
				displayName: 'EAN',
				name: 'EAN',
				type: 'string',
				default: '',
				description: 'Filter by exact EAN',
			},
			{
				displayName: 'Is Active',
				name: 'isActive',
				type: 'boolean',
				default: true,
				description: 'Whether to include only active or only inactive products',
			},
			{
				displayName: 'Primary Supplier ID',
				name: 'primarySupplierId',
				type: 'number',
				default: 0,
				description: 'Filter to products whose primary supplier matches this contact ID',
			},
			{
				displayName: 'Product ID',
				name: 'productId',
				type: 'string',
				default: '',
				description:
					'Filter by product ID. ID set syntax supported: single, range (100-200), or comma list.',
			},
			{
				displayName: 'Product Name',
				name: 'productName',
				type: 'string',
				default: '',
				description: 'Filter by product name (partial match)',
			},
			{
				displayName: 'Product Type ID',
				name: 'productTypeId',
				type: 'number',
				default: 0,
				description: 'Filter by product type ID',
			},
			{
				displayName: 'SKU',
				name: 'SKU',
				type: 'string',
				default: '',
				description: 'Filter by exact SKU',
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				default: 'LIVE',
				options: [
					{ name: 'Discontinued', value: 'DISCONTINUED' },
					{ name: 'End Of Line', value: 'ENDOFLINE' },
					{ name: 'Live', value: 'LIVE' },
				],
				description: 'Filter by product lifecycle status',
			},
			{
				displayName: 'Stock Tracked',
				name: 'stockTracked',
				type: 'boolean',
				default: true,
				description: 'Whether to include only stock-tracked or only non-stock-tracked products',
			},
			{
				displayName: 'UPC',
				name: 'UPC',
				type: 'string',
				default: '',
				description: 'Filter by exact UPC',
			},
			{
				displayName: 'Updated On (From)',
				name: 'updatedOnFrom',
				type: 'dateTime',
				default: '',
				description: 'Return products last updated on or after this date/time',
			},
			{
				displayName: 'Updated On (To)',
				name: 'updatedOnTo',
				type: 'dateTime',
				default: '',
				description: 'Return products last updated on or before this date/time',
			},
		],
	},
	{
		displayName: 'Sort',
		name: 'productSort',
		type: 'collection',
		placeholder: 'Add Sort',
		default: {},
		displayOptions: { show: { resource: ['product'], operation: ['getMany'] } },
		description:
			'Optional: sort results by a product-search column. Default Brightpearl order is by productId ascending.',
		options: [
			{
				displayName: 'Direction',
				name: 'direction',
				type: 'options',
				default: 'DESC',
				options: [
					{ name: 'Ascending', value: 'ASC' },
					{ name: 'Descending', value: 'DESC' },
				],
			},
			{
				displayName: 'Sort By',
				name: 'sortBy',
				type: 'options',
				default: 'createdOn',
				options: [
					{ name: 'Barcode', value: 'barcode' },
					{ name: 'Brand ID', value: 'brandId' },
					{ name: 'Category ID', value: 'categoryId' },
					{ name: 'Created On', value: 'createdOn' },
					{ name: 'EAN', value: 'EAN' },
					{ name: 'ISBN', value: 'ISBN' },
					{ name: 'Is Active', value: 'isActive' },
					{ name: 'MPN', value: 'MPN' },
					{ name: 'Primary Supplier ID', value: 'primarySupplierId' },
					{ name: 'Product ID', value: 'productId' },
					{ name: 'Product Name', value: 'productName' },
					{ name: 'Product Type ID', value: 'productTypeId' },
					{ name: 'SKU', value: 'SKU' },
					{ name: 'Status', value: 'status' },
					{ name: 'Stock Tracked', value: 'stockTracked' },
					{ name: 'UPC', value: 'UPC' },
					{ name: 'Updated On', value: 'updatedOn' },
				],
			},
		],
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		typeOptions: { minValue: 1 },
		displayOptions: {
			show: { resource: ['product'], operation: ['getMany'], returnAll: [false] },
		},
		description: 'Max number of results to return',
	},
	{
		displayName: 'First Result',
		name: 'firstResult',
		type: 'number',
		default: 1,
		typeOptions: { minValue: 1 },
		displayOptions: {
			show: { resource: ['product'], operation: ['getMany'], returnAll: [false] },
		},
		description:
			'1-indexed starting position. Combine with Limit to paginate. Use the _pagination metadata on returned items to see how many total results exist.',
	},
	{
		displayName: 'Batching',
		name: 'batching',
		type: 'collection',
		placeholder: 'Add Batching Option',
		default: {},
		displayOptions: {
			show: { resource: ['product'], operation: ['getMany'], returnAll: [true] },
		},
		description:
			'Optional: pace the page-by-page fetch so large queries do not exhaust the Brightpearl quota and trip the rate-limit retry loop.',
		options: [
			{
				displayName: 'Delay Between Pages (Ms)',
				name: 'pageDelayMs',
				type: 'number',
				default: 0,
				typeOptions: { minValue: 0 },
				description:
					'How long to wait between consecutive page requests. Try 500–1000 if you are hitting 503 errors on large fetches.',
			},
			{
				displayName: 'Page Size',
				name: 'pageSize',
				type: 'number',
				default: 200,
				typeOptions: { minValue: 1, maxValue: 200 },
				description:
					'How many results per Brightpearl page request. Lower values use more API calls but each call is cheaper against the quota.',
			},
		],
	},

	// ─── CREATE ───────────────────────────────────────────────────────────────
	{
		displayName: 'Product Name',
		name: 'productName',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['product'], operation: ['create'] } },
		description: 'The product name as shown in the Brightpearl channel',
	},
	{
		displayName: 'Additional Fields',
		name: 'productAdditionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['product'], operation: ['create'] } },
		options: [
			{
				displayName: 'Barcode',
				name: 'barcode',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Brand ID',
				name: 'brandId',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Category',
				name: 'category',
				type: 'string',
				default: '',
				description: 'Category code for the Brightpearl sales channel',
			},
			{
				displayName: 'EAN',
				name: 'ean',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Short Description',
				name: 'shortDescription',
				type: 'string',
				typeOptions: { rows: 3 },
				default: '',
			},
			{
				displayName: 'SKU',
				name: 'sku',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Tax Code ID',
				name: 'taxCodeId',
				type: 'number',
				default: 0,
				description: 'Financial tax code ID for this product',
			},
			{
				displayName: 'Track Stock',
				name: 'stockTracked',
				type: 'boolean',
				default: true,
			},
		],
	},
];
